Flag Presets
Skylumz/Sollumz pull request #750
Opened 2023-09-08 19:37 UTC by Reszolute

| Changelog |
[+] Fixed the blacklist. (Can't delete default presets now) 
[+] Added a confirmation when deleting custom flag presets. 
[+] Added icons.

Preview:
https://github.com/Skylumz/Sollumz/assets/113695236/d2576752-73ce-4aa8-b875-6e2c4438a4d3

2023-09-08 19:43 UTC, ook3D commented
Balls

2023-09-08 20:15 UTC, alexguirre requested changes
When deleting a blacklisted preset, it still shows the confirmation dialog before showing the "Cannot delete" message. Should just show the message directly.

2023-09-08 20:15 UTC, alexguirre commented on ybn/operators.py
> +    confirm_delete = bpy.props.BoolProperty(default=False)
Unused property, remove it.

2023-09-08 20:15 UTC, alexguirre commented on ybn/operators.py
> +        ]
Unindent the `]` 4 spaces.

2023-09-16 11:12 UTC, alexguirre approved these changes

2023-09-16 11:14 UTC, closed without merging